baseURL = 'http://example.org/'
languageCode = 'es'
title = 'Arte hasta decir basta'
theme = 'ananke'
googleAnalytics = "G-FSVBN1N3B9"
canonifyURLs = true
enableRobotsTXT = true
[markup.goldmark.renderer]
unsafe= true